version: '3.9'

services:
  web:
    build: .
    command: gunicorn openpromptbank.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=openpromptbank.settings.production
      - POSTGRES_DB=openpromptbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=openpromptbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword

volumes:
  postgres_data:
